sylius_fixtures:
    suites:
        app:
            fixtures:
                wishlist:
                    options:
                        count: 5
                supplier:
                    options:
                        count: 10
