sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/Resources/config/admin_routing.yml"
    prefix: /admin

app_wishlist:
    resource: |
        alias: app.wishlist
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index', 'delete']
        grid: app_admin_wishlist
    type: sylius.resource
    prefix: /admin
